# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java CI adhoc testing

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 7
    continue-on-error: true
    strategy:
      matrix:
        tag: [ HEAD, rel/commons-net-3.10.0, rel/commons-net-3.9.0 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        persist-credentials: false
        ref: ${{ matrix.tag }}
    - name: Set up JDK
      uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Test NET710
      run: |
        cat <<'EOD' >src/test/java/org/apache/commons/net/ftp/parser/FTPTimestampNET710Test.java
        package org.apache.commons.net.ftp.parser;


        import java.text.ParseException;
        import java.util.Calendar;
        import java.util.Locale;
        import java.util.TimeZone;

        import org.junit.jupiter.api.Test;

        /**
        * Test NET710
        */
        public class FTPTimestampNET710Test {

            @Test
            public void testNet710() throws ParseException {
                Calendar serverTime = Calendar.getInstance(TimeZone.getTimeZone("EDT"), Locale.US);
                serverTime.set(2022, 2, 16, 14, 0);
                Calendar p = new FTPTimestampParserImpl().parseTimestamp("Mar 13 02:33", serverTime);
                System.out.println(p);
            }

        }
        EOD
        mvn -V --batch-mode --file pom.xml --no-transfer-progress test -Dtest=FTPTimestampNET710Test -Drat.skip
    # - name: Look for deletefile failures
    #   run: |
    #     mvn -V --batch-mode --file pom.xml --no-transfer-progress test -Dtest=TFTPServerPathTest
    #     mvn -V --batch-mode --file pom.xml --no-transfer-progress test -Dtest=TFTPServerPathTest
    #     mvn -V --batch-mode --file pom.xml --no-transfer-progress test -Dtest=TFTPServerPathTest
    #     mvn -V --batch-mode --file pom.xml --no-transfer-progress test -Dtest=TFTPServerPathTest
    #     mvn -V --batch-mode --file pom.xml --no-transfer-progress test -Dtest=TFTPServerPathTest
    #     mvn -V --batch-mode --file pom.xml --no-transfer-progress test -Dtest=TFTPServerPathTest
    #     mvn -V --batch-mode --file pom.xml --no-transfer-progress test -Dtest=TFTPServerPathTest
    #     mvn -V --batch-mode --file pom.xml --no-transfer-progress test -Dtest=TFTPServerPathTest
    #     mvn -V --batch-mode --file pom.xml --no-transfer-progress test -Dtest=TFTPServerPathTest
    # - name: Test exec function
    #   run: |
    #     mvn -q exec:java
    #     mvn -q exec:java -D"exec.arguments=FTPClientExample"
